services:
  api:
    build:
      dockerfile: api/Dockerfile
      context: . # Use root context, so rdfgen can be pulled in
    container_name: lucos_media_metadata_api
    ports: 
      - $PORT:$PORT
    image: lucas42/lucos_media_metadata_api:${VERSION:-latest}
    volumes:
      - "db:/var/lib/media-metadata/"
      - "exports:/var/lib/exports/"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      - CLIENT_KEYS
      - LOGANNE_ENDPOINT
      - RDF_OUTPUT_PATH=/var/lib/exports/all-media.ttl
      - MEDIA_METADATA_MANAGER_ORIGIN=https://media-metadata.l42.eu
      - PORT
      - KEY_LUCOS_EOLAS
      - DEBUG=1
  exporter:
    build:
      dockerfile: exporter/Dockerfile
      context: . # Use root context, so rdfgen can be pulled in
    container_name: lucos_media_metadata_api_exporter
    image: lucas42/lucos_media_metadata_api_exporter:${VERSION:-latest}
    volumes:
      - db:/data:ro
      - exports:/exports
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "crond"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      - SQLITE_DB_PATH=/data/media.sqlite
      - RDF_OUTPUT_PATH=/exports/all-media.ttl
      - SCHEDULE_TRACKER_ENDPOINT
      - MEDIA_METADATA_MANAGER_ORIGIN=https://media-metadata.l42.eu

volumes:
  db:
  exports: